### PR TITLE
Add link libraries and definitions for MinGW support

### PR DESCRIPTION
**Pull request by nightlark**
Adds definitions and target link libraries needed to build with MinGW and MSYS Makefiles.

Asio may have some large issues when trying to compile it under Cygwin:
- type conversions that mainly appear to involve the volatile keyword (e.g. `long int*` to `volatile long unsigned int*`)
- functions that appear to be compiler intrinsics can't be found (e.g. _InterlockedIncrement); not sure if these are available with Cygwin's gcc compiler or if MSVC is required, may also be tied to the type conversion issue

I've tried disabling I/O completion ports in Asio (ASIO_DISABLE_IOCP) though the same problem functions are used elsewhere, and disabling use of WIN32_LEAN_AND_MEAN (ASIO_NO_WIN32_LEAN_AND_MEAN) didn't resolve the issue with finding matching functions. Getting builds working for Cygwin looks like it could be tricky if it is an Asio issue.

### CODE REVIEW

**Comment by nightlark** [comment]
Switching to 32-bit Cygwin doesn’t have the same type conversion and function matching errors in Asio.

Though the smaller number of errors about not having expected parenthesis is still in Asio header files.

**Comment by phlptp** [comment]
did you need me to try it on a local cygwin?  My take a me a bit to get that set up again

**Comment by nightlark** [comment]
I don't have a local Cygwin environment set up either. It looks like the error is Asio trying to use SEH when building for Cygwin, and use of a Windows-only `_snwprintf` function that isn't available with Cygwin.

I'm thinking maybe Asio shouldn't be defining `ASIO_WINDOWS` at all for Cygwin builds so it uses the POSIX functions provided by Cygwin instead of the Windows API.

**Comment by nightlark** [comment]
Just checked the Appveyor config for HELICS and noticed it had been setting `-DHELICS_DISABLE_ASIO=ON` (and running 64-bit Cygwin). I'm thinking the best we can do is force `GMLC_NETWORKING_DISABLE_ASIO` when building with Cygwin.

**Comment by phlptp** [comment]
Are we expecting an update to make the remaining two tests to pass?

**Comment by nightlark** [comment]
I'm disabling use of asio for Cygwin; I think to support it we'd need to fix asio support for Cygwin.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
