### PR TITLE
Add tcp tests

### PR DESCRIPTION
**Pull request by aenkoji1**

### CODE REVIEW

**Comment by phlptp** [comment]
probably should set the test timeout to be much shorter,  Do we know which test is timing out?

**Comment by aenkoji1** [comment]
> probably should set the test timeout to be much shorter, Do we know which test is timing out?

For the most part I'm planning on setting the timeout to about 200ms. When setting up a tcpConnection to server, I was getting a few timeouts, but the length of the timeout shouldn't matter for those.

**Comment by phlptp** [comment]
No the whole test timeout,  I would expect these test to run fairly quickly so if the entire test suite takes more than 60 seconds we can be pretty confident something has gone wrong,  no reason to let it go 1500 seconds.

**Comment by aenkoji1** [comment]
@phlptp the ubuntu test is failing due to "listen: Address already in use" error. The address is using localhost in the tests. Is there another one I should use instead?

**Comment by phlptp** [comment]
It would probably indicate the port is in use.   I don't think it would be interface.

**Comment by nightlark** [comment]
This sounds like the listening socket/server wasn't shutdown after a previous test case ran.

**Comment by aenkoji1** [comment]
> This sounds like the listening socket/server isn't getting shutdown at the end of a previous test case.

That might be it. I'm guessing closing the io_context does not close the socket. Do we have to manually close the sockets in the test cases?

**Comment by phlptp** [comment]
No, closing the context would trigger all the callbacks and async operations for a socket, but the socket itself would still be open and operating.  It could still call operations that don't depend on the context.  So it should be closed separately.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
